version: '3.8'

services:
  app:
    image: spring-plus:latest
    container_name: spring-plus-container
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - IAM_ACCESS_KEY=${IAM_ACCESS_KEY}
      - IAM_SECRET_KEY=${IAM_SECRET_KEY}
      - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - SECRET_KEY=${SECRET_KEY}
    restart: always