name: Deploy to EC2 with Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Spring Boot App
        run: ./gradlew bootJar

      - name: Build Docker image
        run: docker build -t spring-plus:latest .

      - name: Save Docker image as tar
        run: docker save spring-plus:latest -o app-image.tar

      - name: Copy Docker image file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: app-image.tar
          target: ~/deploy

      - name: Copy Docker compose file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: docker-compose.yml
          target: ~/deploy

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/deploy
            echo "${{ secrets.APP_ENV }}" > .env
            docker load -i app-image.tar
            docker-compose down || true
            docker-compose up -d